### ISSUE TITLE
Error running tufte-pandoc-css

### ISSUE THREAD

**Issue by robsalasco** [jez/pandoc-sidenote#1]
Hi! I'm trying to run tufte-pandoc-css but I have this error

```
robsalasco@leucippus:~/Desktop/tufte-pandoc-css$ make
pandoc \
		--katex \
		--smart \
		--section-divs \
		--from markdown+tex_math_single_backslash \
		--filter pandoc-sidenote \
		--to html5 \
		--template=tufte \
		--css tufte.css --css pandoc.css --css pandoc-solarized.css --css tufte-extra.css \
		--output docs/index.html \
		docs/index.md
pandoc-sidenote: Error in $: mempty
CallStack (from HasCallStack):
  error, called at ./Text/Pandoc/JSON.hs:108:64 in pandoc-types-1.17-KRy4e6Qs9AIJIlwwj55hmZ:Text.Pandoc.JSON
pandoc: Error running filter pandoc-sidenote
Filter returned error status 1
make: *** [docs/index.html] Error 83
```

Can you help me please?

**Comment by jez** [comment]
Hm, I can't seem to reproduce this.

- What operating system are you on?
- Did you compile `pandoc-sidenote` from source, or did you use a precompiled binary?
- If you compiled from source, did you use Stack to build the project?

If you answer those questions I might be able to suggest a solution, but off the top of my head I can't think of anything.

**Comment by robsalasco** [comment]
- I'm running MacOS Sierra
- I used brew

**Comment by jez** [comment]
Also, version of pandoc are you using? You might want to try upgrading to
version 1.18 and try again.

**Comment by robsalasco** [comment]
now it's working @jez !!! please add the requeriment of pandoc 1.18 :)

**Comment by jez** [comment]
Done. Thanks for your patience!

**Comment by gwern** [comment]
I don't see any Pandoc version constraint in the cabal file. Also, this issue is still marked open.

**Comment by jez** [comment]
Is that not what these lines accomplish?

https://github.com/jez/pandoc-sidenote/blob/master/stack.yaml#L8-L9

**Comment by gwern** [comment]
I noted you edited the stack file, but I'm not familiar with how stack works - isn't it a totally different packaging system from cabal and so the constraint wouldn't apply to anyone installing using `cabal install` or from Hackage?

Incidentally, while it would be good to upload this to Hackage, right now `cabal check` tells me that there needs to be version dependencies put on `base`. I've been out of Haskell long enough that I don't know what the right thing to do there would be, so I'm telling you.

**Comment by jez** [comment]
Alright, thanks for the heads up. I'm not all that familiar with Haskell packaging either. I might look into it.
